Repository Azure/Telepathy, pull requests merged in 2019-11, with the labels that each got.

#107 Consolidate duplicated env vars
  deploy/StartTelepathyService.ps1
  src/TelepathyCommon/TelepathyConstants.cs
  src/soa/BrokerLauncher/Program.cs
  src/soa/CcpServiceHost/Program.cs
  src/soa/SessionLauncher/Impls/SessionLaunchers/AzureBatch/AzureBatchSessionLauncher.cs
Labels: priority 1

#117 Change yaml to validate arm templete.
  azure-pipelines.yml
Labels: priority 0

#115 Feature/dev template
  azure-pipelines.yml
  deploy/azuredeploy.json
  deploy/azuredeploy.parameters.json
Labels: priority 0, usability
